DROP TABLE IF EXISTS notify_log;
DROP TABLE IF EXISTS notify_channels;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS local_otp_codes;
DROP TABLE IF EXISTS local_accounts;
DROP TABLE IF EXISTS auth_settings;
DROP TABLE IF EXISTS identity_configs;
DROP TABLE IF EXISTS external_identities;
ALTER TABLE IF EXISTS departments DROP CONSTRAINT IF EXISTS departments_lead_member_fk;
DROP TABLE IF EXISTS members;
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS role_permissions;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS organizations;
