// Generated by the shadcn CLI. The one local edit across this directory
// is the icon source: lucide is swapped for the console's own set, since
// DESIGN.md 6.2 pins the app to a single 1.5px-stroke family and rules
// out mixing icon libraries. A `text-` class on each glyph is deliberate
// -- it opts the glyph out of the `svg:not([class*='text-'])` tint rules
// the console wrappers use to leave vendor marks their own colour.

import * as React from "react"
import { Checkbox as CheckboxPrimitive } from "radix-ui"

import { Icon } from "@/components/console/icon"
import { cn } from "@/lib/utils"

function Checkbox({
  className,
  ...props
}: React.ComponentProps<typeof CheckboxPrimitive.Root>) {
  return (
    <CheckboxPrimitive.Root
      data-slot="checkbox"
      className={cn(
        "peer size-4 shrink-0 rounded-[4px] border border-input shadow-xs transition-shadow outline-none focus-visible:border-ring focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-destructive/20 data-[state=checked]:border-primary data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground dark:bg-input/30 dark:aria-invalid:ring-destructive/40 dark:data-[state=checked]:bg-primary",
        className
      )}
      {...props}
    >
      <CheckboxPrimitive.Indicator
        data-slot="checkbox-indicator"
        className="grid place-content-center text-current transition-none"
      >
        <Icon name="check" size={11} stroke={2.6} className="size-3.5 text-current" />
      </CheckboxPrimitive.Indicator>
    </CheckboxPrimitive.Root>
  )
}

export { Checkbox }
